Fix behavior when dialog cancelled

diff --git a/git-credential-libsecret-add-https b/git-credential-libsecret-add-https
--- a/git-credential-libsecret-add-https
+++ b/git-credential-libsecret-add-https
@@ -17,13 +17,13 @@ credentials_form() {
 
 store_with_helper() {
 	read -r DOMAIN
-	test -n "${DOMAIN:-}" || return 1
+	test -n "${DOMAIN:-}"
 
 	read -r USERNAME
-	test -n "${USERNAME:-}" || return 1
+	test -n "${USERNAME:-}"
 
 	read -r PASSWORD
-	test -n "${PASSWORD:-}" || return 1
+	test -n "${PASSWORD:-}"
 
 	git-credential-libsecret store >/dev/null <<EOF
 protocol=https
@@ -33,10 +33,20 @@ password=${PASSWORD}
 EOF
 }
 
-if credentials_form | store_with_helper
+clean_tmp() {
+	unlink $TMP 2>/dev/null || true
+}
+
+TMP=$(mktemp -t git-credential-libsecret-add-https.XXXXXX)
+trap clean_tmp INT TERM HUP QUIT EXIT
+
+if credentials_form >$TMP
 then
-	exec seahorse
-else
-	zenity --error --text "Failed to store credentials"
+	if store_with_helper <$TMP
+	then
+		exec seahorse
+	else
+		zenity --error --text "Failed to store credentials"
+	fi
 fi
 
